version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: dsquiz_db
    environment:
      POSTGRES_DB: dsquiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dsquiznet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: dsquiz_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dsquiz
    networks:
      - dsquiznet
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    container_name: dsquiz_frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - dsquiznet
    restart: unless-stopped

volumes:
  pgdata:

networks:
  dsquiznet:
    driver: bridge